# This file is inspired by nlohmann
# You can find the original file here: https://github.com/nlohmann/json/blob/develop/appveyor.yml

version: '{build}'

os: 
  - Visual Studio 2015

environment:
  matrix:
  - additional_flags: "/EHsc"
  - additional_flags: "/EHsc /std:c++14 /utf-8"
  - additional_flags: "/EHsc /permissive- /std:c++14 /utf-8"
  
init: []

install:
  - git submodule update --init --recursive

build_script:
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE ( IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( SET GEN="Visual Studio 15 2017") ELSE ( SET GEN="Visual Studio 16 2019") )
  - cmake . -G%GEN% -DKANGARU_BUILD_EXAMPLES=true -DKANGARU_TEST=true -DKANGARU_TEST_CXX14=true -DCMAKE_CXX_FLAGS="%additional_flags%"
  - cmake --build .

test_script:
  - ctest .

