name: All OS
on: [push, pull_request]

jobs:
  apple-clang:
    name: AppleClang XCode ${{ matrix.xcode }} MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [macos-13]
        xcode: [14.3, 15.2]
        include:
          - xcode: 13
            os: macos-12
            arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '3508985146f1b1d248c67ead13f8f54be5b4f5da'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  linux-clang:
    name: Clang ${{ matrix.clang }} Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang: [11, 12, 13, 14, 15, 16, 17, 18, 19]

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix develop .#ci-clang${{ matrix.clang }} --command bash -c "cmake --preset ci-linux && cmake --build --preset ci-linux && ctest --preset ci-linux"

  linux-gcc:
    name: GCC ${{ matrix.gcc }} Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-22.04] 
        gcc: [11, 12, 13]

    steps:
      - uses: actions/checkout@v4

      # Minimum GCC version required for vcpkg
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '3508985146f1b1d248c67ead13f8f54be5b4f5da'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
          platform: ${{ matrix.arch }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  windows-msvc:
    runs-on: windows-latest
    name: MSVC ${{ matrix.msvc-version }} Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        arch: [x64]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.26.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          useVcpkgToolchainFile: true
          vcpkgGitCommitId: '3508985146f1b1d248c67ead13f8f54be5b4f5da'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

