name: All OS
on: [push, pull_request]

jobs:
  apple-clang:
    name: AppleClang XCode ${{ matrix.xcode }} MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode: [16.2]

    steps:
      - uses: actions/checkout@v4

      - name: get-cmake
        uses: lukka/get-cmake@v3.29.6

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'b2cb0da531c2f1f740045bfe7c4dac59f0b2b69c'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: 'run cmake'
        uses: lukka/run-cmake@v10
        with:
          configurepreset: 'ci-macos'
          buildpreset: 'ci-macos'
          testpreset: 'ci-macos'
          configurepresetcmdstring: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  linux-clang:
    name: Clang ${{ matrix.clang }} Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang: [16, 17, 18, 19]

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci-clang${{ matrix.clang }}"

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  linux-gcc:
    name: GCC ${{ matrix.gcc }} Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gcc: [11, 12, 13, 14]

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: ".#ci-gcc${{ matrix.gcc }}"

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-linux'
          buildPreset: 'ci-linux'
          testPreset: 'ci-linux'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  windows-msvc:
    runs-on: windows-latest
    name: MSVC ${{ matrix.msvc-version }} Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        arch: [x64]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.29.6

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          useVcpkgToolchainFile: true
          vcpkgGitCommitId: 'b2cb0da531c2f1f740045bfe7c4dac59f0b2b69c'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci-windows'
          buildPreset: 'ci-windows'
          testPreset: 'ci-windows'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

