name: All OS
on: [push, pull_request]

jobs:
  apple-clang:
    name: AppleClang XCode ${{ matrix.xcode }} MacOS (hash-mode ${{ matrix.hash-typeid }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        cxx14: [On]
        cxx17: [On]
        arch: [x64]
        os: [macos-12]
        xcode: [14]
        triplet: ["x64-osx"]

    steps: 
      - uses: actions/checkout@v2

      - name: get-cmake
        uses: lukka/get-cmake@v3.23.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c1b768b0d6bc9b05d6272d604496d33a3faedd90'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`, `-DKANGARU_TEST_CXX14=${{ matrix.cxx14 }}`, `-DKANGARU_TEST_CXX17=${{ matrix.cxx17 }}`, `-DKANGARU_HASH_TYPE_ID=${{ matrix.hash-typeid }}`]'

  linux-clang:
    name: Clang ${{ matrix.clang }} Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-22.04]
        clang: [11, 12, 13, 14, 15]
        include:
          - clang: 10
            os: ubuntu-20.04
            arch: x64

    steps: 
      - uses: actions/checkout@v2

      # Minimum GCC version required for vcpkg
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.23.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c1b768b0d6bc9b05d6272d604496d33a3faedd90'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang }}
          platform: ${{ matrix.arch }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  linux-gcc:
    name: GCC ${{ matrix.gcc }} Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-22.04] 
        gcc: [11, 12]

    steps: 
      - uses: actions/checkout@v2

      # Minimum GCC version required for vcpkg
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.23.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c1b768b0d6bc9b05d6272d604496d33a3faedd90'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
          platform: ${{ matrix.arch }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

  windows-msvc:
    runs-on: windows-latest
    name: MSVC ${{ matrix.msvc-version }} Windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        arch: [x64]
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: egor-tensin/vs-shell@v2
        with:
          arch: ${{ matrix.arch }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.23.0

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'c1b768b0d6bc9b05d6272d604496d33a3faedd90'
          # Since the cache must be invalidated when content of the vcpkg.json file changes, let's
          # compute its hash and append this to the computed cache's key.
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ci'
          buildPreset: 'ci'
          testPreset: 'ci'
          configurePresetCmdString: '[`--preset`, `$[env.CONFIGURE_PRESET_NAME]`]'

